
F åB
Û‘='$¯ãL‘¡¿„J•%ÑW£f≈w‰	¸g ê51(êÁG*Ek®’õ\?¢∏˛ªqŒÉí&àQ·’
›’
ë’
Ê
Ù√Íû"jornadaŒ
±
orgA-orderer-comú-----BEGIN CERTIFICATE-----
MIICfDCCAiKgAwIBAgIURigf+ZZUKXbwZlWgf4fcZ0xIj34wCgYIKoZIzj0EAwIw
cTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQDDBNj
YS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAxNVoXDTMyMTAzMTE3MzAx
NVowbjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
VQQHDAdSYWxlaWdoMRAwDgYDVQQLDAdvcmRlcmVyMSIwIAYDVQQDDBlvcmRlcmVy
MS5vcmdBLW9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9CJ2
JZgNN8zGwgyY1gBRsEWUU2oWU3JOuoZgaBcl3Jo1JNJBbSwYJJBIh8q2O3PYYRKj
hCpeEopyRW9C0N+rDaOBmjCBlzAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIw
ADBWBgNVHREETzBNhwTAqAAaghlvcmRlcmVyMS5vcmdBLW9yZGVyZXIuY29tghlv
cmRlcmVyMS1vcmdBLW9yZGVyZXItY29tgglsb2NhbGhvc3SHBH8AAAEwHwYDVR0j
BBgwFoAUAmU4EyLMlgEO78rUS99L6hRE9eIwCgYIKoZIzj0EAwIDSAAwRQIhAOPC
VJ/rdnvGDpLNziUzFhdEILij0MNqXvM+ThmHAnTEAiA1/rIqqwwmWBYfiMKstzbJ
C+cRhUxHAfw6bbfwjpeRBw==
-----END CERTIFICATE-----
y—fCI•ñÛæ,Ô]ä]>Ò”Üe®U˛Ü§Õ
’ªœªÒI
OrdererÂIÃ8
orgA-orderer-com∑8˙6
MSPÚ6Á6‰6
orgA-orderer-comÂ-----BEGIN CERTIFICATE-----
MIICtDCCAlqgAwIBAgIUP/s4VIljATdGGLVkIScDO80kUt0wCgYIKoZIzj0EAwIw
cTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQDDBNj
YS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAwNVoXDTMzMDEyOTE3MzAw
NVowcTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
VQQHDAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQD
DBNjYS5vcmdBLW9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
Y46MMSGzErMuQX/bAj3+eXtJ5aToSB84syyz2uNrqAoQUJQJLWT8gj+nwQGn4MhX
YUY7pid32GydEqF+US4XdqOBzzCBzDAdBgNVHQ4EFgQUAmU4EyLMlgEO78rUS99L
6hRE9eIwHwYDVR0jBBgwFoAUAmU4EyLMlgEO78rUS99L6hRE9eIwDwYDVR0TAQH/
BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
AQUFBwMCMEoGA1UdEQRDMEGHBMCoABqCE2NhLm9yZ0Etb3JkZXJlci5jb22CE2Nh
LW9yZ0Etb3JkZXJlci1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNI
ADBFAiAVk5orHk/mHDPWY8cfFcqG24+cvyXHGrL+v+DCU9sJRwIhAIsILB3t3Sjb
pZuTIktFpx7jy/skhHHSwkhOWomOHj+i
-----END CERTIFICATE-----
"å-----BEGIN CERTIFICATE-----
MIICcTCCAhegAwIBAgIURigf+ZZUKXbwZlWgf4fcZ0xIj30wCgYIKoZIzj0EAwIw
cTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQDDBNj
YS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAxMFoXDTMyMTAzMTE3MzAx
MFowaTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
VQQHDAdSYWxlaWdoMQ4wDAYDVQQLDAVhZG1pbjEfMB0GA1UEAwwWQWRtaW5Ab3Jn
QS1vcmRlcmVyLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMVwgQetF1R3
ZXWN7XpRgyO1K82gJDp1TOXlgevNRdmzom4b4gYIa2Td9JnyttJAhGN511OFfT2k
T1ISr82SQhCjgZQwgZEwDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAwUAYD
VR0RBEkwR4cEwKgAGoIWQWRtaW5Ab3JnQS1vcmRlcmVyLmNvbYIWQWRtaW5Ab3Jn
QS1vcmRlcmVyLWNvbYIJbG9jYWxob3N0hwR/AAABMB8GA1UdIwQYMBaAFAJlOBMi
zJYBDu/K1EvfS+oURPXiMAoGCCqGSM49BAMCA0gAMEUCIQDBG1gSFWpzjHvkbYRw
T2NF4+MZxRpkk2gO57LAX3ESGQIgeqiv8rx4GWVleYQjNCcCtutEaXJGWp9R4DBs
t1Z76Yc=
-----END CERTIFICATE-----
B
SHA2SHA256J˘-----BEGIN CERTIFICATE-----
MIICwTCCAmagAwIBAgIUPP+r3BsWkORU59ygm1r4lzBm1ngwCgYIKoZIzj0EAwIw
dDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMR8wHQYDVQQDDBZ0
bHNjYS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAwNVoXDTMzMDEyOTE3
MzAwNVowdDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAw
DgYDVQQHDAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMR8wHQYD
VQQDDBZ0bHNjYS5vcmdBLW9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
AQcDQgAEUWmx9XWS0DFrG3eH8md5smYPB9XUXYnPCRblevqJn3kUOFXqxMDOsWnh
4ZL30XXcSdgd+Lj96Y1T9DOdPJMhjqOB1TCB0jAdBgNVHQ4EFgQU0YP+Vz8/7my7
v6XwBVyM6WV6Ng0wHwYDVR0jBBgwFoAU0YP+Vz8/7my7v6XwBVyM6WV6Ng0wDwYD
VR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUH
AwEGCCsGAQUFBwMCMFAGA1UdEQRJMEeHBMCoABqCFnRsc2NhLm9yZ0Etb3JkZXJl
ci5jb22CFnRsc2NhLW9yZ0Etb3JkZXJlci1jb22CCWxvY2FsaG9zdIcEfwAAATAK
BggqhkjOPQQDAgNJADBGAiEAtJQASMmiO0kiAx/HBtk9w9GNP/UiO5keASKWCOUN
5SgCIQC5RtXFth8Beoyd9XIoc+D786sKT6G30kN6jg9dHCDG5w==
-----END CERTIFICATE-----
ZÃ
Â-----BEGIN CERTIFICATE-----
MIICtDCCAlqgAwIBAgIUP/s4VIljATdGGLVkIScDO80kUt0wCgYIKoZIzj0EAwIw
cTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQDDBNj
YS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAwNVoXDTMzMDEyOTE3MzAw
NVowcTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
VQQHDAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQD
DBNjYS5vcmdBLW9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
Y46MMSGzErMuQX/bAj3+eXtJ5aToSB84syyz2uNrqAoQUJQJLWT8gj+nwQGn4MhX
YUY7pid32GydEqF+US4XdqOBzzCBzDAdBgNVHQ4EFgQUAmU4EyLMlgEO78rUS99L
6hRE9eIwHwYDVR0jBBgwFoAUAmU4EyLMlgEO78rUS99L6hRE9eIwDwYDVR0TAQH/
BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
AQUFBwMCMEoGA1UdEQRDMEGHBMCoABqCE2NhLm9yZ0Etb3JkZXJlci5jb22CE2Nh
LW9yZ0Etb3JkZXJlci1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNI
ADBFAiAVk5orHk/mHDPWY8cfFcqG24+cvyXHGrL+v+DCU9sJRwIhAIsILB3t3Sjb
pZuTIktFpx7jy/skhHHSwkhOWomOHj+i
-----END CERTIFICATE-----
clientÓ
Â-----BEGIN CERTIFICATE-----
MIICtDCCAlqgAwIBAgIUP/s4VIljATdGGLVkIScDO80kUt0wCgYIKoZIzj0EAwIw
cTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQDDBNj
YS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAwNVoXDTMzMDEyOTE3MzAw
NVowcTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
VQQHDAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQD
DBNjYS5vcmdBLW9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
Y46MMSGzErMuQX/bAj3+eXtJ5aToSB84syyz2uNrqAoQUJQJLWT8gj+nwQGn4MhX
YUY7pid32GydEqF+US4XdqOBzzCBzDAdBgNVHQ4EFgQUAmU4EyLMlgEO78rUS99L
6hRE9eIwHwYDVR0jBBgwFoAUAmU4EyLMlgEO78rUS99L6hRE9eIwDwYDVR0TAQH/
BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
AQUFBwMCMEoGA1UdEQRDMEGHBMCoABqCE2NhLm9yZ0Etb3JkZXJlci5jb22CE2Nh
LW9yZ0Etb3JkZXJlci1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNI
ADBFAiAVk5orHk/mHDPWY8cfFcqG24+cvyXHGrL+v+DCU9sJRwIhAIsILB3t3Sjb
pZuTIktFpx7jy/skhHHSwkhOWomOHj+i
-----END CERTIFICATE-----
peer"Ô
Â-----BEGIN CERTIFICATE-----
MIICtDCCAlqgAwIBAgIUP/s4VIljATdGGLVkIScDO80kUt0wCgYIKoZIzj0EAwIw
cTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQDDBNj
YS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAwNVoXDTMzMDEyOTE3MzAw
NVowcTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
VQQHDAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQD
DBNjYS5vcmdBLW9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
Y46MMSGzErMuQX/bAj3+eXtJ5aToSB84syyz2uNrqAoQUJQJLWT8gj+nwQGn4MhX
YUY7pid32GydEqF+US4XdqOBzzCBzDAdBgNVHQ4EFgQUAmU4EyLMlgEO78rUS99L
6hRE9eIwHwYDVR0jBBgwFoAUAmU4EyLMlgEO78rUS99L6hRE9eIwDwYDVR0TAQH/
BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
AQUFBwMCMEoGA1UdEQRDMEGHBMCoABqCE2NhLm9yZ0Etb3JkZXJlci5jb22CE2Nh
LW9yZ0Etb3JkZXJlci1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNI
ADBFAiAVk5orHk/mHDPWY8cfFcqG24+cvyXHGrL+v+DCU9sJRwIhAIsILB3t3Sjb
pZuTIktFpx7jy/skhHHSwkhOWomOHj+i
-----END CERTIFICATE-----
admin*Ò
Â-----BEGIN CERTIFICATE-----
MIICtDCCAlqgAwIBAgIUP/s4VIljATdGGLVkIScDO80kUt0wCgYIKoZIzj0EAwIw
cTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQDDBNj
YS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAwNVoXDTMzMDEyOTE3MzAw
NVowcTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
VQQHDAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQD
DBNjYS5vcmdBLW9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
Y46MMSGzErMuQX/bAj3+eXtJ5aToSB84syyz2uNrqAoQUJQJLWT8gj+nwQGn4MhX
YUY7pid32GydEqF+US4XdqOBzzCBzDAdBgNVHQ4EFgQUAmU4EyLMlgEO78rUS99L
6hRE9eIwHwYDVR0jBBgwFoAUAmU4EyLMlgEO78rUS99L6hRE9eIwDwYDVR0TAQH/
BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
AQUFBwMCMEoGA1UdEQRDMEGHBMCoABqCE2NhLm9yZ0Etb3JkZXJlci5jb22CE2Nh
LW9yZ0Etb3JkZXJlci1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNI
ADBFAiAVk5orHk/mHDPWY8cfFcqG24+cvyXHGrL+v+DCU9sJRwIhAIsILB3t3Sjb
pZuTIktFpx7jy/skhHHSwkhOWomOHj+i
-----END CERTIFICATE-----
ordererAdmins":
Admins0&" 
orgA-orderer-comAdmins"9
Readers.$  
orgA-orderer-comAdmins"9
Writers.$  
orgA-orderer-comAdmins*AdminsË
ConsensusType÷À
etcdraftæ
ß
192.168.0.26ê7à-----BEGIN CERTIFICATE-----
MIICbjCCAhOgAwIBAgIUDc9h5ywEoIPg7iZ2322+znuFy8kwCgYIKoZIzj0EAwIw
dDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMR8wHQYDVQQDDBZ0
bHNjYS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAxNVoXDTMyMTAzMTE3
MzAxNVowXDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAw
DgYDVQQHDAdSYWxlaWdoMSIwIAYDVQQDDBlvcmRlcmVyMS5vcmdBLW9yZGVyZXIu
Y29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDsRwLDwSipiMjEMUbXoFW+6O
cYz9klLD2yDQ/wKK7zQNalVjd8p3+pLnjzHaizi8oOJQE+p7q9iGLyEqCYuewqOB
mjCBlzAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADBWBgNVHREETzBNhwTA
qAAaghlvcmRlcmVyMS5vcmdBLW9yZGVyZXIuY29tghlvcmRlcmVyMS1vcmdBLW9y
ZGVyZXItY29tgglsb2NhbGhvc3SHBH8AAAEwHwYDVR0jBBgwFoAU0YP+Vz8/7my7
v6XwBVyM6WV6Ng0wCgYIKoZIzj0EAwIDSQAwRgIhAIw2QzF+etUzt1Zw/B73aVuZ
I9uKh+bLw7pBR/34xwlCAiEA0e3RiGos2GBoAATqKqqf1M0nucyhZHOYbdvGQ+y/
0LQ=
-----END CERTIFICATE-----
"à-----BEGIN CERTIFICATE-----
MIICbjCCAhOgAwIBAgIUDc9h5ywEoIPg7iZ2322+znuFy8kwCgYIKoZIzj0EAwIw
dDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMR8wHQYDVQQDDBZ0
bHNjYS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAxNVoXDTMyMTAzMTE3
MzAxNVowXDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAw
DgYDVQQHDAdSYWxlaWdoMSIwIAYDVQQDDBlvcmRlcmVyMS5vcmdBLW9yZGVyZXIu
Y29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDsRwLDwSipiMjEMUbXoFW+6O
cYz9klLD2yDQ/wKK7zQNalVjd8p3+pLnjzHaizi8oOJQE+p7q9iGLyEqCYuewqOB
mjCBlzAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADBWBgNVHREETzBNhwTA
qAAaghlvcmRlcmVyMS5vcmdBLW9yZGVyZXIuY29tghlvcmRlcmVyMS1vcmdBLW9y
ZGVyZXItY29tgglsb2NhbGhvc3SHBH8AAAEwHwYDVR0jBBgwFoAU0YP+Vz8/7my7
v6XwBVyM6WV6Ng0wCgYIKoZIzj0EAwIDSQAwRgIhAIw2QzF+etUzt1Zw/B73aVuZ
I9uKh+bLw7pBR/34xwlCAiEA0e3RiGos2GBoAATqKqqf1M0nucyhZHOYbdvGQ+y/
0LQ=
-----END CERTIFICATE-----

500ms
 (ÄÄÄAdmins"
	BatchSize
ÄÄ¿1ÄÄ Admins
BatchTimeout
2sAdmins
ChannelRestrictionsAdmins$
Capabilities


V2_0 Admins""
Writers	
WritersAdmins""
Admins

AdminsAdmins"*
BlockValidation	
WritersAdmins""
Readers	
ReadersAdmins*Admins˜n
ApplicationÁnæ6
orgA-com±6,
AnchorPeers

192.168.0.26é7Admins„3
MSP€3–3Õ3
orgA-com¨-----BEGIN CERTIFICATE-----
MIICiTCCAi6gAwIBAgIUa5jlNn8RJe2+aU2bncAJs75joogwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0Eu
Y29tMB4XDTIzMDIwMTE3MzAyMFoXDTMzMDEyOTE3MzAyMFowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0EuY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEq041MAb1OGgiotoij3H/95a8j0KUZnI7sI608rM2
jjiHIIv8qPC35FcB+zmwVZtSK7/uWcfrp+0Uee+KdwenxKOBwTCBvjAdBgNVHQ4E
FgQUo0iHDD/XPgi6+h3GwfFbF3ktx5swHwYDVR0jBBgwFoAUo0iHDD/XPgi6+h3G
wfFbF3ktx5swDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdBLmNvbYIMY2ExLW9yZ0EtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSQAwRgIhAMbN+Zy+i/Ny/Ujf0BMU3PQ/pSkcGF8wx7TZ4EV5zjS6AiEA8VLI
9++pWAINKM0c2x4lwcGSuWUIHeljKo6sLASB7Vg=
-----END CERTIFICATE-----
"◊-----BEGIN CERTIFICATE-----
MIICSTCCAfCgAwIBAgIUHAaI5xQuzogVsWI8xClYQBc8TGIwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0Eu
Y29tMB4XDTIzMDIwMTE3MzAyNFoXDTMyMTAzMTE3MzAyNFowYTELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMQ4w
DAYDVQQLDAVhZG1pbjEXMBUGA1UEAwwOQWRtaW5Ab3JnQS5jb20wWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAATmkWA/pbB3bHZ1WycGl2+uv0IerpqcDTJ/GR7Sy32x
gB3Zjoii3TTEOPixd9tOS7F/Ub4C+cPCGwxpfyBmaEgGo4GEMIGBMA4GA1UdDwEB
/wQEAwIHgDAMBgNVHRMBAf8EAjAAMEAGA1UdEQQ5MDeHBMCoABqCDkFkbWluQG9y
Z0EuY29tgg5BZG1pbkBvcmdBLWNvbYIJbG9jYWxob3N0hwR/AAABMB8GA1UdIwQY
MBaAFKNIhww/1z4IuvodxsHxWxd5LcebMAoGCCqGSM49BAMCA0cAMEQCIFpLD63Q
d3MQn+Jxl+ZQwj5uTfjU0FrvEEUkLFRgFslyAiApVV3XmzkzHqZf0X9EjNgQKNse
iy6esBd3QKvQ92Z5HQ==
-----END CERTIFICATE-----
B
SHA2SHA256Jº-----BEGIN CERTIFICATE-----
MIIClTCCAjqgAwIBAgIUNeRDs45zJCgj/5StwHNlJrlu8SwwCgYIKoZIzj0EAwIw
ZTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdBLmNvbTEYMBYGA1UEAwwPdGxzY2ExLm9y
Z0EuY29tMB4XDTIzMDIwMTE3MzAyMFoXDTMzMDEyOTE3MzAyMFowZTELMAkGA1UE
BhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdo
MREwDwYDVQQKDAhvcmdBLmNvbTEYMBYGA1UEAwwPdGxzY2ExLm9yZ0EuY29tMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEHYty8iPt1mvoPEhU8nw0maBhuQtuEB2
kg/omWTSl59inoai3muOcFRAcsoqmTJ+SKgMnR57Eoq/S4CyJEWYOKOBxzCBxDAd
BgNVHQ4EFgQUjM2RFUwMRe3ftZuYb7nAsB1kZp0wHwYDVR0jBBgwFoAUjM2RFUwM
Re3ftZuYb7nAsB1kZp0wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYw
HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEIGA1UdEQQ7MDmHBMCoABqC
D3Rsc2NhMS5vcmdBLmNvbYIPdGxzY2ExLW9yZ0EtY29tgglsb2NhbGhvc3SHBH8A
AAEwCgYIKoZIzj0EAwIDSQAwRgIhAMd3etrk6R6XcF+KrCxLAI7xjXwy9Q+wzy3l
/OZ7/zmGAiEAtZODCBYjElCs/eRjDVW4NDAEGNegQZPxjRjlSMcjzeg=
-----END CERTIFICATE-----
ZË∑
¨-----BEGIN CERTIFICATE-----
MIICiTCCAi6gAwIBAgIUa5jlNn8RJe2+aU2bncAJs75joogwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0Eu
Y29tMB4XDTIzMDIwMTE3MzAyMFoXDTMzMDEyOTE3MzAyMFowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0EuY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEq041MAb1OGgiotoij3H/95a8j0KUZnI7sI608rM2
jjiHIIv8qPC35FcB+zmwVZtSK7/uWcfrp+0Uee+KdwenxKOBwTCBvjAdBgNVHQ4E
FgQUo0iHDD/XPgi6+h3GwfFbF3ktx5swHwYDVR0jBBgwFoAUo0iHDD/XPgi6+h3G
wfFbF3ktx5swDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdBLmNvbYIMY2ExLW9yZ0EtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSQAwRgIhAMbN+Zy+i/Ny/Ujf0BMU3PQ/pSkcGF8wx7TZ4EV5zjS6AiEA8VLI
9++pWAINKM0c2x4lwcGSuWUIHeljKo6sLASB7Vg=
-----END CERTIFICATE-----
clientµ
¨-----BEGIN CERTIFICATE-----
MIICiTCCAi6gAwIBAgIUa5jlNn8RJe2+aU2bncAJs75joogwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0Eu
Y29tMB4XDTIzMDIwMTE3MzAyMFoXDTMzMDEyOTE3MzAyMFowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0EuY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEq041MAb1OGgiotoij3H/95a8j0KUZnI7sI608rM2
jjiHIIv8qPC35FcB+zmwVZtSK7/uWcfrp+0Uee+KdwenxKOBwTCBvjAdBgNVHQ4E
FgQUo0iHDD/XPgi6+h3GwfFbF3ktx5swHwYDVR0jBBgwFoAUo0iHDD/XPgi6+h3G
wfFbF3ktx5swDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdBLmNvbYIMY2ExLW9yZ0EtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSQAwRgIhAMbN+Zy+i/Ny/Ujf0BMU3PQ/pSkcGF8wx7TZ4EV5zjS6AiEA8VLI
9++pWAINKM0c2x4lwcGSuWUIHeljKo6sLASB7Vg=
-----END CERTIFICATE-----
peer"∂
¨-----BEGIN CERTIFICATE-----
MIICiTCCAi6gAwIBAgIUa5jlNn8RJe2+aU2bncAJs75joogwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0Eu
Y29tMB4XDTIzMDIwMTE3MzAyMFoXDTMzMDEyOTE3MzAyMFowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0EuY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEq041MAb1OGgiotoij3H/95a8j0KUZnI7sI608rM2
jjiHIIv8qPC35FcB+zmwVZtSK7/uWcfrp+0Uee+KdwenxKOBwTCBvjAdBgNVHQ4E
FgQUo0iHDD/XPgi6+h3GwfFbF3ktx5swHwYDVR0jBBgwFoAUo0iHDD/XPgi6+h3G
wfFbF3ktx5swDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdBLmNvbYIMY2ExLW9yZ0EtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSQAwRgIhAMbN+Zy+i/Ny/Ujf0BMU3PQ/pSkcGF8wx7TZ4EV5zjS6AiEA8VLI
9++pWAINKM0c2x4lwcGSuWUIHeljKo6sLASB7Vg=
-----END CERTIFICATE-----
admin*∏
¨-----BEGIN CERTIFICATE-----
MIICiTCCAi6gAwIBAgIUa5jlNn8RJe2+aU2bncAJs75joogwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0Eu
Y29tMB4XDTIzMDIwMTE3MzAyMFoXDTMzMDEyOTE3MzAyMFowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdBLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ0EuY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEq041MAb1OGgiotoij3H/95a8j0KUZnI7sI608rM2
jjiHIIv8qPC35FcB+zmwVZtSK7/uWcfrp+0Uee+KdwenxKOBwTCBvjAdBgNVHQ4E
FgQUo0iHDD/XPgi6+h3GwfFbF3ktx5swHwYDVR0jBBgwFoAUo0iHDD/XPgi6+h3G
wfFbF3ktx5swDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdBLmNvbYIMY2ExLW9yZ0EtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSQAwRgIhAMbN+Zy+i/Ny/Ujf0BMU3PQ/pSkcGF8wx7TZ4EV5zjS6AiEA8VLI
9++pWAINKM0c2x4lwcGSuWUIHeljKo6sLASB7Vg=
-----END CERTIFICATE-----
ordererAdmins"G
Writers<2.
 
orgA-com
orgA-comAdmins"2
Admins( 
orgA-comAdmins"7
Endorsement( 
orgA-comAdmins"[
ReadersPFB 
orgA-com
orgA-com
orgA-comAdmins*Admins¶6
orgX-comô6À3
MSP√3∏3µ3
orgX-com®-----BEGIN CERTIFICATE-----
MIIChzCCAi6gAwIBAgIUardL2HNhBFe8WVEX3N/mYah2ss8wCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1gu
Y29tMB4XDTIzMDIwMTE3MzAzOVoXDTMzMDEyOTE3MzAzOVowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1guY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEXSCyD7+GDI4TQSia5346+stnovArW5bYfOspRPS6
fn5H8x5ZUQl4BRty9ajG+6l9KnoscE/PFfGm9Kh1qT67MKOBwTCBvjAdBgNVHQ4E
FgQUKStqJI6bk0ZfNtROCGc6Wg/o4zowHwYDVR0jBBgwFoAUKStqJI6bk0ZfNtRO
CGc6Wg/o4zowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdYLmNvbYIMY2ExLW9yZ1gtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDRwAwRAIgCH+pxjbQwcHRAwM2Zj6kg6997974Mg7wqqcaJjgCo/0CICLJIvwN
RPBWy1szLSZDIWbUmHffhzg3NLK0WgtUEibQ
-----END CERTIFICATE-----
"◊-----BEGIN CERTIFICATE-----
MIICSTCCAfCgAwIBAgIUK15FbKJaSLWfh6s2fUr7AWRYrCIwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1gu
Y29tMB4XDTIzMDIwMTE3MzA0NFoXDTMyMTAzMTE3MzA0NFowYTELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMQ4w
DAYDVQQLDAVhZG1pbjEXMBUGA1UEAwwOQWRtaW5Ab3JnWC5jb20wWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAAQuvBU40ynonksUiWvoBStaAb8vAlPXgjUgxFLpWPBe
LV9lt4NQ3LZ4dq7sgH+RO1oun50Hsawo6hk6H6efNFepo4GEMIGBMA4GA1UdDwEB
/wQEAwIHgDAMBgNVHRMBAf8EAjAAMEAGA1UdEQQ5MDeHBMCoABqCDkFkbWluQG9y
Z1guY29tgg5BZG1pbkBvcmdYLWNvbYIJbG9jYWxob3N0hwR/AAABMB8GA1UdIwQY
MBaAFCkraiSOm5NGXzbUTghnOloP6OM6MAoGCCqGSM49BAMCA0cAMEQCIG8xkGwl
c0KHcOszOnugY5Z0iajOn/mFmJ3n3C0incMGAiAPptbRtx3+OKEjYpMeoGJ67jFX
mC6cP2/Lpu6lmvgwsw==
-----END CERTIFICATE-----
B
SHA2SHA256J∏-----BEGIN CERTIFICATE-----
MIICkzCCAjqgAwIBAgIUAieJpJXop6P9fYuNFtKh4m63QtQwCgYIKoZIzj0EAwIw
ZTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdYLmNvbTEYMBYGA1UEAwwPdGxzY2ExLm9y
Z1guY29tMB4XDTIzMDIwMTE3MzA0MFoXDTMzMDEyOTE3MzA0MFowZTELMAkGA1UE
BhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdo
MREwDwYDVQQKDAhvcmdYLmNvbTEYMBYGA1UEAwwPdGxzY2ExLm9yZ1guY29tMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgF4j26FePy/J6+B+m1CiRiT2QfWgb1N8
Jm2+EXqjzoHo/IHw4+hWRkCHzChVPEeRFZ5z5OxBQpIMq0FhKZTxS6OBxzCBxDAd
BgNVHQ4EFgQUtMRwPu4bdJiM55lI5MVOGp72RqwwHwYDVR0jBBgwFoAUtMRwPu4b
dJiM55lI5MVOGp72RqwwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYw
HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEIGA1UdEQQ7MDmHBMCoABqC
D3Rsc2NhMS5vcmdYLmNvbYIPdGxzY2ExLW9yZ1gtY29tgglsb2NhbGhvc3SHBH8A
AAEwCgYIKoZIzj0EAwIDRwAwRAIgKcmMYaTYOYoQHdjsXpnRU5z64Xld/ekqc/hW
FgVUi2ICIAWoqk4UtjcykmuFPbGTPq7A19BsIL/JKblXgbD9zImp
-----END CERTIFICATE-----
Zÿ≥
®-----BEGIN CERTIFICATE-----
MIIChzCCAi6gAwIBAgIUardL2HNhBFe8WVEX3N/mYah2ss8wCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1gu
Y29tMB4XDTIzMDIwMTE3MzAzOVoXDTMzMDEyOTE3MzAzOVowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1guY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEXSCyD7+GDI4TQSia5346+stnovArW5bYfOspRPS6
fn5H8x5ZUQl4BRty9ajG+6l9KnoscE/PFfGm9Kh1qT67MKOBwTCBvjAdBgNVHQ4E
FgQUKStqJI6bk0ZfNtROCGc6Wg/o4zowHwYDVR0jBBgwFoAUKStqJI6bk0ZfNtRO
CGc6Wg/o4zowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdYLmNvbYIMY2ExLW9yZ1gtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDRwAwRAIgCH+pxjbQwcHRAwM2Zj6kg6997974Mg7wqqcaJjgCo/0CICLJIvwN
RPBWy1szLSZDIWbUmHffhzg3NLK0WgtUEibQ
-----END CERTIFICATE-----
client±
®-----BEGIN CERTIFICATE-----
MIIChzCCAi6gAwIBAgIUardL2HNhBFe8WVEX3N/mYah2ss8wCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1gu
Y29tMB4XDTIzMDIwMTE3MzAzOVoXDTMzMDEyOTE3MzAzOVowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1guY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEXSCyD7+GDI4TQSia5346+stnovArW5bYfOspRPS6
fn5H8x5ZUQl4BRty9ajG+6l9KnoscE/PFfGm9Kh1qT67MKOBwTCBvjAdBgNVHQ4E
FgQUKStqJI6bk0ZfNtROCGc6Wg/o4zowHwYDVR0jBBgwFoAUKStqJI6bk0ZfNtRO
CGc6Wg/o4zowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdYLmNvbYIMY2ExLW9yZ1gtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDRwAwRAIgCH+pxjbQwcHRAwM2Zj6kg6997974Mg7wqqcaJjgCo/0CICLJIvwN
RPBWy1szLSZDIWbUmHffhzg3NLK0WgtUEibQ
-----END CERTIFICATE-----
peer"≤
®-----BEGIN CERTIFICATE-----
MIIChzCCAi6gAwIBAgIUardL2HNhBFe8WVEX3N/mYah2ss8wCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1gu
Y29tMB4XDTIzMDIwMTE3MzAzOVoXDTMzMDEyOTE3MzAzOVowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1guY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEXSCyD7+GDI4TQSia5346+stnovArW5bYfOspRPS6
fn5H8x5ZUQl4BRty9ajG+6l9KnoscE/PFfGm9Kh1qT67MKOBwTCBvjAdBgNVHQ4E
FgQUKStqJI6bk0ZfNtROCGc6Wg/o4zowHwYDVR0jBBgwFoAUKStqJI6bk0ZfNtRO
CGc6Wg/o4zowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdYLmNvbYIMY2ExLW9yZ1gtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDRwAwRAIgCH+pxjbQwcHRAwM2Zj6kg6997974Mg7wqqcaJjgCo/0CICLJIvwN
RPBWy1szLSZDIWbUmHffhzg3NLK0WgtUEibQ
-----END CERTIFICATE-----
admin*¥
®-----BEGIN CERTIFICATE-----
MIIChzCCAi6gAwIBAgIUardL2HNhBFe8WVEX3N/mYah2ss8wCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1gu
Y29tMB4XDTIzMDIwMTE3MzAzOVoXDTMzMDEyOTE3MzAzOVowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMREw
DwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1guY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEXSCyD7+GDI4TQSia5346+stnovArW5bYfOspRPS6
fn5H8x5ZUQl4BRty9ajG+6l9KnoscE/PFfGm9Kh1qT67MKOBwTCBvjAdBgNVHQ4E
FgQUKStqJI6bk0ZfNtROCGc6Wg/o4zowHwYDVR0jBBgwFoAUKStqJI6bk0ZfNtRO
CGc6Wg/o4zowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdEQQ1MDOHBMCoABqCDGNhMS5v
cmdYLmNvbYIMY2ExLW9yZ1gtY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDRwAwRAIgCH+pxjbQwcHRAwM2Zj6kg6997974Mg7wqqcaJjgCo/0CICLJIvwN
RPBWy1szLSZDIWbUmHffhzg3NLK0WgtUEibQ
-----END CERTIFICATE-----
ordererAdmins,
AnchorPeers

192.168.0.26å7Admins"2
Admins( 
orgX-comAdmins"7
Endorsement( 
orgX-comAdmins"[
ReadersPFB 
orgX-com
orgX-com
orgX-comAdmins"G
Writers<2.
 
orgX-com
orgX-comAdmins*Admins$
Capabilities


V2_0 Admins""
Readers	
ReadersAdmins""
Writers	
WritersAdmins""
Admins

AdminsAdmins"*
Endorsement
EndorsementAdmins"3
LifecycleEndorsement
EndorsementAdmins*Admins-
BlockDataHashingStructureˇˇˇˇAdminsB
OrdererAddresses.
192.168.0.26:7056/Channel/Orderer/Admins*

Consortium
SampleConsortiumAdmins$
Capabilities


V2_0 Admins&
HashingAlgorithm
SHA256Admins""
Readers	
ReadersAdmins""
Writers	
WritersAdmins""
Admins

AdminsAdmins*Admins»
¸
ô
Ù√Íû"jornadaÅ
‰
orgX-com◊-----BEGIN CERTIFICATE-----
MIICSTCCAfCgAwIBAgIUK15FbKJaSLWfh6s2fUr7AWRYrCIwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1gu
Y29tMB4XDTIzMDIwMTE3MzA0NFoXDTMyMTAzMTE3MzA0NFowYTELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMQ4w
DAYDVQQLDAVhZG1pbjEXMBUGA1UEAwwOQWRtaW5Ab3JnWC5jb20wWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAAQuvBU40ynonksUiWvoBStaAb8vAlPXgjUgxFLpWPBe
LV9lt4NQ3LZ4dq7sgH+RO1oun50Hsawo6hk6H6efNFepo4GEMIGBMA4GA1UdDwEB
/wQEAwIHgDAMBgNVHRMBAf8EAjAAMEAGA1UdEQQ5MDeHBMCoABqCDkFkbWluQG9y
Z1guY29tgg5BZG1pbkBvcmdYLWNvbYIJbG9jYWxob3N0hwR/AAABMB8GA1UdIwQY
MBaAFCkraiSOm5NGXzbUTghnOloP6OM6MAoGCCqGSM49BAMCA0cAMEQCIG8xkGwl
c0KHcOszOnugY5Z0iajOn/mFmJ3n3C0incMGAiAPptbRtx3+OKEjYpMeoGJ67jFX
mC6cP2/Lpu6lmvgwsw==
-----END CERTIFICATE-----
◊›>º,Ω¨ÇÎ2ÉÒÈf†SY4√¸ßÄù›	
ã
jornadaa_
ApplicationPL
orgX-com@
MSP "

Admins "
Endorsement "
Readers "
Writers úô
ApplicationâÑ
orgX-comx,
AnchorPeers

192.168.0.26å7Admins
MSP "

Admins "
Endorsement "
Readers "
Writers *AdminsÃ
Å
‰
orgX-com◊-----BEGIN CERTIFICATE-----
MIICSTCCAfCgAwIBAgIUK15FbKJaSLWfh6s2fUr7AWRYrCIwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMREwDwYDVQQKDAhvcmdYLmNvbTEVMBMGA1UEAwwMY2ExLm9yZ1gu
Y29tMB4XDTIzMDIwMTE3MzA0NFoXDTMyMTAzMTE3MzA0NFowYTELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMQ4w
DAYDVQQLDAVhZG1pbjEXMBUGA1UEAwwOQWRtaW5Ab3JnWC5jb20wWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAAQuvBU40ynonksUiWvoBStaAb8vAlPXgjUgxFLpWPBe
LV9lt4NQ3LZ4dq7sgH+RO1oun50Hsawo6hk6H6efNFepo4GEMIGBMA4GA1UdDwEB
/wQEAwIHgDAMBgNVHRMBAf8EAjAAMEAGA1UdEQQ5MDeHBMCoABqCDkFkbWluQG9y
Z1guY29tgg5BZG1pbkBvcmdYLWNvbYIJbG9jYWxob3N0hwR/AAABMB8GA1UdIwQY
MBaAFCkraiSOm5NGXzbUTghnOloP6OM6MAoGCCqGSM49BAMCA0cAMEQCIG8xkGwl
c0KHcOszOnugY5Z0iajOn/mFmJ3n3C0incMGAiAPptbRtx3+OKEjYpMeoGJ67jFX
mC6cP2/Lpu6lmvgwsw==
-----END CERTIFICATE-----
˘∆F_^◊ïÿ Ów‚Jèé„{˜ª#‚ôF0D ?Ò°°C∞ “ƒ5∆t6zs!π‹=è\ŸL¬bûÅ >Ç•Ô>Vt.B.’≠	≤7√p⁄”–‚Re≈›«ÇYG0E! Ç[êúÂåp∆~çg ùÃ“'≈∏óz´BA[$ v≤s¿Ãˆïd”w£
9»L°ÔAryÄÏ'ô¸û0BF0D T}©U∫ \ß©§`mã‰JÿK€ÿ≠Cîi9π`å \ÇñëŸ
5Äk^t©:uË
,A‡‡~eˆ…&8ôΩ
Æ

	

ö
Œ
±
orgA-orderer-comú-----BEGIN CERTIFICATE-----
MIICfDCCAiKgAwIBAgIURigf+ZZUKXbwZlWgf4fcZ0xIj34wCgYIKoZIzj0EAwIw
cTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBvcmdBLW9yZGVyZXIuY29tMRwwGgYDVQQDDBNj
YS5vcmdBLW9yZGVyZXIuY29tMB4XDTIzMDIwMTE3MzAxNVoXDTMyMTAzMTE3MzAx
NVowbjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYD
VQQHDAdSYWxlaWdoMRAwDgYDVQQLDAdvcmRlcmVyMSIwIAYDVQQDDBlvcmRlcmVy
MS5vcmdBLW9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9CJ2
JZgNN8zGwgyY1gBRsEWUU2oWU3JOuoZgaBcl3Jo1JNJBbSwYJJBIh8q2O3PYYRKj
hCpeEopyRW9C0N+rDaOBmjCBlzAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIw
ADBWBgNVHREETzBNhwTAqAAaghlvcmRlcmVyMS5vcmdBLW9yZGVyZXIuY29tghlv
cmRlcmVyMS1vcmdBLW9yZGVyZXItY29tgglsb2NhbGhvc3SHBH8AAAEwHwYDVR0j
BBgwFoAUAmU4EyLMlgEO78rUS99L6hRE9eIwCgYIKoZIzj0EAwIDSAAwRQIhAOPC
VJ/rdnvGDpLNziUzFhdEILij0MNqXvM+ThmHAnTEAiA1/rIqqwwmWBYfiMKstzbJ
C+cRhUxHAfw6bbfwjpeRBw==
-----END CERTIFICATE-----
˘SÌI! ∏vÚ ñ%ëÖéP0‹‹íæG0E! ∫ã9á∑,ÿç–`Fc58OtÔµ¨QN·j'l2˚—©„ &ÚœÈ˙}wÑ∫ÈNMﬂÏkzV§"ëDîlÒß†TÓè


 
 
 