---
- name: Create appstudent run script
  template:
    src: "{{ pjroot }}/playbooks/ops/appstudent/templates/appstudent.j2"
    dest: "{{ pjroot }}/vars/run/appstudent.sh"
    mode: +x

- name: Run the appstudent application
  command: >-
    docker run -d --network {{ NETNAME }} --name appstudent --hostname appstudent
    --expose 8080
    -e ORG_NAME={{ CURRENT_ORG }}
    -v /var/run/docker.sock:/var/run/docker.sock
    -v {{ hostroot }}/vars:/vars
    -v {{ hostroot }}/vars/app/:/go/src/github.com/app
    --entrypoint /vars/run/appstudent.sh
    {{ LANGUAGEENVS['node'] }}
  register: runstates

- name: appstudent run
  when: runstates.rc != 0
  debug:
    msg: "{{ runstates.stderr_lines }}"
  tags: [print_action]

- name: appstudent run
  when: runstates.rc == 0
  debug:
    msg: "Application in node completed successfully"
  tags: [print_action]
